### DISCUSSION TITLE
Enable target overrides for package? (netcoredbg macOS arm64)

### DISCUSSION THREAD

**Discussion by Cliffback** [mason-org/mason.nvim#1628] [API suggestions]
Netcoredbg doesn't have native arm64 macOS binaries in their releases, and as far as I can tell, it doesn't seem like it will happen in the near future either. The problem with this is that netcoredbg installed via Mason won't work on Apple Silicon machines at all.

As a quick and dirty way to solve it, I wrote a plugin for integrating my compiled binaries with nvim-dap: [netcoredbg-macOS-arm64.nvim](https://github.com/Cliffback/netcoredbg-macOS-arm64.nvim)

But this doesn't really solve the issue with being able to use it with Mason, so I was wondering if it is possible to make target_overrides the same way version_overrides work in the registry?

Then it would be possible to specify a different repo for a specific target platform. As en example, then I could host the binaries for macOS arm64, and a target override in the package.yaml for netcoredbg could have an alternate repo than the rest of the targets. I put this in Example 2 below.

An alternative would be to make each target also possible to have an id that overrides the source id and would mean fewer lines. I put this in example 1.

For netcoredbg at least, one of these soulutions would make it way easier for the folks on newer macs. 

# **Example 1:**
```
source:
  id: pkg:github/Samsung/netcoredbg@3.0.0-1018
  asset:
    - target: [darwin_x64]
      id_override: pkg:github/Cliffback//netcoredbg-macOS-arm64.nvim@3.0.0-1018
      file: netcoredbg-osx-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: [darwin_x64]
      file: netcoredbg-osx-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: linux_arm64_gnu
      file: netcoredbg-linux-arm64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: linux_x64_gnu
      file: netcoredbg-linux-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: win_x64
      file: netcoredbg-win64.zip
      bin: netcoredbg/netcoredbg.exe
```

# **Example 2:**
```
source:
  # renovate:versioning=loose
  id: pkg:github/Samsung/netcoredbg@3.0.0-1018
  asset:
    - target: [darwin_x64]
      file: netcoredbg-osx-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: linux_arm64_gnu
      file: netcoredbg-linux-arm64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: linux_x64_gnu
      file: netcoredbg-linux-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
    - target: win_x64
      file: netcoredbg-win64.zip
      bin: netcoredbg/netcoredbg.exe
version_overrides:
  constraint: target=darwin_arm64
  id: pkg:github/Cliffback//netcoredbg-macOS-arm64.nvim@3.0.0-1018
  asset:
    - target: [darwin_arm64]
      file: netcoredbg-osx-amd64.tar.gz:libexec/
      bin: exec:libexec/netcoredbg/netcoredbg
```
    
I don't know if this is a feasible solution, or if it is out of the question to handle it this way, so just take it for what its worth :)

Anyways, for netcoredbg, darwin_arm64 should be removed from the netcoredbg registry as long as it points to the samsung source repo, as the binary there is just for amd64, and I spent a long while debugging why it didn't work, before I found the cause

Cheers
